-- Builder initial schema. Enums are stored as their names (varchar(32)), lists as text[], maps/specs as jsonb.

CREATE TABLE users (
    id            uuid        PRIMARY KEY,
    user_name     text        NOT NULL,
    display_name  text        NOT NULL,
    password_hash text        NOT NULL,
    is_admin      boolean     NOT NULL DEFAULT false,
    created_at    timestamptz NOT NULL
);
CREATE UNIQUE INDEX ux_users_user_name ON users (user_name);

CREATE TABLE connections (
    id              uuid        PRIMARY KEY,
    name            text        NOT NULL,
    type            varchar(32) NOT NULL,          -- AzureDevOps | Git
    url             text        NOT NULL,
    username        text,
    token_protected text,                          -- Data Protection ciphertext
    created_at      timestamptz NOT NULL
);

CREATE TABLE pipelines (
    id                uuid         PRIMARY KEY,
    name              varchar(200) NOT NULL,
    connection_id     uuid         REFERENCES connections (id),
    repository_url    text         NOT NULL,
    default_branch    text         NOT NULL,
    taskfile_path     text         NOT NULL,
    entry_task        text,
    last_build_number integer      NOT NULL DEFAULT 0,   -- optimistic concurrency token
    created_at        timestamptz  NOT NULL
);
CREATE UNIQUE INDEX ux_pipelines_name ON pipelines (name);

CREATE TABLE builds (
    id           uuid        PRIMARY KEY,
    pipeline_id  uuid        NOT NULL REFERENCES pipelines (id),
    number       integer     NOT NULL,
    branch       text        NOT NULL,
    commit       text,
    entry_task   text        NOT NULL,
    variables    jsonb       NOT NULL DEFAULT '{}',
    status       varchar(32) NOT NULL,          -- Planning | Running | Canceling | Succeeded | Failed | Canceled
    requested_by text        NOT NULL,
    error        text,
    queued_at    timestamptz NOT NULL,
    started_at   timestamptz,
    finished_at  timestamptz
);
CREATE UNIQUE INDEX ux_builds_pipeline_number ON builds (pipeline_id, number);
CREATE INDEX ix_builds_status ON builds (status);
CREATE INDEX ix_builds_queued_at ON builds (queued_at);

CREATE TABLE build_jobs (
    id               uuid        PRIMARY KEY,
    build_id         uuid        NOT NULL REFERENCES builds (id) ON DELETE CASCADE,
    key              text        NOT NULL,
    task_name        text        NOT NULL,
    description      text,
    "order"          integer     NOT NULL,
    depends_on       text[]      NOT NULL DEFAULT '{}',
    task_vars        jsonb       NOT NULL DEFAULT '{}',
    labels           text[]      NOT NULL DEFAULT '{}',
    artifacts        text[]      NOT NULL DEFAULT '{}',
    has_commands     boolean     NOT NULL,
    approval         jsonb,
    deploy           jsonb,
    status           varchar(32) NOT NULL,
    agent_id         uuid,
    agent_name       text,
    exit_code        integer,
    error            text,
    ready_at         timestamptz,
    started_at       timestamptz,
    finished_at      timestamptz,
    approved_by      text,
    approved_at      timestamptz,
    approval_comment text
);
CREATE UNIQUE INDEX ux_build_jobs_build_key ON build_jobs (build_id, key);
CREATE INDEX ix_build_jobs_status ON build_jobs (status);
CREATE INDEX ix_build_jobs_agent_id ON build_jobs (agent_id);

CREATE TABLE log_lines (
    id        bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    build_id  uuid        NOT NULL REFERENCES builds (id) ON DELETE CASCADE,
    job_id    uuid        NOT NULL REFERENCES build_jobs (id) ON DELETE CASCADE,
    timestamp timestamptz NOT NULL,
    stream    varchar(32) NOT NULL,             -- Out | Err | System
    text      text        NOT NULL
);
CREATE INDEX ix_log_lines_job_id ON log_lines (job_id, id);
CREATE INDEX ix_log_lines_build_id ON log_lines (build_id);

CREATE TABLE artifacts (
    id           uuid        PRIMARY KEY,
    build_id     uuid        NOT NULL REFERENCES builds (id) ON DELETE CASCADE,
    job_id       uuid        NOT NULL REFERENCES build_jobs (id) ON DELETE CASCADE,
    name         text        NOT NULL,
    size_bytes   bigint      NOT NULL,
    storage_path text        NOT NULL,
    created_at   timestamptz NOT NULL
);
CREATE INDEX ix_artifacts_build_id ON artifacts (build_id);
CREATE INDEX ix_artifacts_job_id ON artifacts (job_id);

CREATE TABLE agents (
    id            uuid        PRIMARY KEY,
    name          text        NOT NULL,
    host_name     text        NOT NULL,
    os            text        NOT NULL,
    version       text        NOT NULL,
    capacity      integer     NOT NULL,
    labels        text[]      NOT NULL DEFAULT '{}',
    enabled       boolean     NOT NULL DEFAULT true,
    online        boolean     NOT NULL DEFAULT false,
    connection_id text,
    last_seen_at  timestamptz,
    created_at    timestamptz NOT NULL
);
CREATE UNIQUE INDEX ux_agents_name ON agents (name);

CREATE TABLE environments (
    id                          uuid        PRIMARY KEY,
    name                        text        NOT NULL,
    type                        varchar(32) NOT NULL,   -- SshDocker | Kubernetes
    requires_approval           boolean     NOT NULL DEFAULT false,
    approvers                   text[]      NOT NULL DEFAULT '{}',
    agent_labels                text[]      NOT NULL DEFAULT '{}',
    host                        text,
    port                        integer     NOT NULL DEFAULT 22,
    username                    text,
    private_key_protected       text,
    kubeconfig_protected        text,
    aks_tenant_id               text,
    aks_client_id               text,
    aks_client_secret_protected text,
    aks_subscription_id         text,
    aks_resource_group          text,
    aks_cluster_name            text,
    aks_admin                   boolean     NOT NULL DEFAULT false,
    created_at                  timestamptz NOT NULL
);
CREATE UNIQUE INDEX ux_environments_name ON environments (name);

-- Deployments are history: they keep their names after builds/environments are cleaned up, so no FKs there.
CREATE TABLE deployments (
    id               uuid        PRIMARY KEY,
    environment_id   uuid        NOT NULL,
    environment_name text        NOT NULL,
    pipeline_id      uuid        NOT NULL,
    build_id         uuid        NOT NULL,
    build_number     integer     NOT NULL,
    job_id           uuid        NOT NULL,
    name             text        NOT NULL,
    compose          text,
    manifests        text,
    url              text,
    status           varchar(32) NOT NULL,   -- Deploying | Active | Failed | Destroying | Destroyed
    output           text,
    created_at       timestamptz NOT NULL,
    updated_at       timestamptz
);
CREATE INDEX ix_deployments_environment_id ON deployments (environment_id);
CREATE INDEX ix_deployments_build_id ON deployments (build_id);
CREATE INDEX ix_deployments_job_id ON deployments (job_id);
